In [1]:
import pandas as pd

# from url 'https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/OxCGRT_latest.csv'
path = 'covid-policy-tracker/data/OxCGRT_latest.csv'
DF = pd.read_csv(path, low_memory=False)
DF

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239299,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220201,NaN,NaN,NaN,NaN,...,NaN,40.74,NaN,49.52,NaN,40.1,NaN,45.83,NaN,0.0
239300,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220202,NaN,NaN,NaN,NaN,...,NaN,40.74,NaN,49.52,NaN,40.1,NaN,45.83,NaN,0.0
239301,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220203,NaN,NaN,NaN,NaN,...,NaN,40.74,NaN,49.52,NaN,40.1,NaN,45.83,NaN,0.0
239302,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220204,NaN,NaN,NaN,NaN,...,NaN,40.74,NaN,49.52,NaN,40.1,NaN,45.83,NaN,0.0
239303,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220205,NaN,NaN,NaN,NaN,...,NaN,40.74,NaN,49.52,NaN,40.1,NaN,45.83,NaN,0.0

In [2]:
UKDF = DF[DF['CountryName'] == 'United Kingdom'].reset_index(drop = True)
UKDF

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
3,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
4,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3830,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220201,1.0,1.0,2.0,1.0,...,41.67,41.67,53.57,53.57,47.4,47.4,50.6,50.6,25.0,25.0
3831,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220202,1.0,1.0,2.0,1.0,...,41.67,41.67,53.57,53.57,47.4,47.4,50.6,50.6,25.0,25.0
3832,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220203,1.0,1.0,2.0,1.0,...,41.67,41.67,53.57,53.57,47.4,47.4,50.6,50.6,25.0,25.0
3833,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220204,1.0,1.0,2.0,1.0,...,41.67,41.67,53.57,53.57,47.4,47.4,50.6,50.6,25.0,25.0
3834,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220205,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

UK = UKDF[UKDF['RegionName'].isna()].reset_index(drop = True)
UK.to_csv('data/COVID_POLICY_UK.csv', index = False)
UK

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
3,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
4,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220201,1.0,0.0,2.0,0.0,...,42.13,42.13,46.43,46.43,47.4,47.4,50.6,50.6,25.0,25.0
763,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220202,1.0,0.0,2.0,0.0,...,42.13,42.13,46.43,46.43,47.4,47.4,50.6,50.6,25.0,25.0
764,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220203,1.0,0.0,2.0,0.0,...,42.13,42.13,46.43,46.43,47.4,47.4,50.6,50.6,25.0,25.0
765,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220204,1.0,0.0,2.0,0.0,...,42.13,42.13,46.43,46.43,47.4,47.4,50.6,50.6,25.0,25.0
766,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220205,NaN,NaN,NaN,NaN,...,NaN,42.13,NaN,46.43,NaN,47.4,NaN,50.6,NaN,25.0

In [4]:
EnglandDF = UKDF[UKDF['RegionName'] == 'England'].reset_index(drop = True)
EnglandDF.to_csv('data/COVID_POLICY_ENGLAND.csv')
EnglandDF

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20220201,1.0,1.0,0.0,NaN,...,20.37,20.37,28.57,28.57,30.21,30.21,30.95,30.95,25.0,25.0
763,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20220202,1.0,1.0,0.0,NaN,...,20.37,20.37,28.57,28.57,30.21,30.21,30.95,30.95,25.0,25.0
764,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20220203,1.0,1.0,0.0,NaN,...,20.37,20.37,28.57,28.57,30.21,30.21,30.95,30.95,25.0,25.0
765,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20220204,1.0,1.0,0.0,NaN,...,20.37,20.37,28.57,28.57,30.21,30.21,30.95,30.95,25.0,25.0
766,United Kingdom,GBR,England,UK_ENG,STATE_TOTAL,20220205,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN